// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd1trj6baevToFIeYaw2ibYS0cyqzQW9A',
    appId: '1:150769916429:web:1cac3da8640b2824695344',
    messagingSenderId: '150769916429',
    projectId: 'restaurant-reservation-2c78f',
    authDomain: 'restaurant-reservation-2c78f.firebaseapp.com',
    storageBucket: 'restaurant-reservation-2c78f.appspot.com',
    measurementId: 'G-ZPNL8YP2FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhJNGtkHnPsNPEqUWysMemH4OwUU9e9zo',
    appId: '1:150769916429:android:2052efdbae47bd80695344',
    messagingSenderId: '150769916429',
    projectId: 'restaurant-reservation-2c78f',
    storageBucket: 'restaurant-reservation-2c78f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhrzKABOGA0k7BGG0s_gbw4ZmH-FbD1gs',
    appId: '1:150769916429:ios:e3eb77df3b5a28de695344',
    messagingSenderId: '150769916429',
    projectId: 'restaurant-reservation-2c78f',
    storageBucket: 'restaurant-reservation-2c78f.appspot.com',
    iosBundleId: 'com.example.restaurantReservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhrzKABOGA0k7BGG0s_gbw4ZmH-FbD1gs',
    appId: '1:150769916429:ios:e3eb77df3b5a28de695344',
    messagingSenderId: '150769916429',
    projectId: 'restaurant-reservation-2c78f',
    storageBucket: 'restaurant-reservation-2c78f.appspot.com',
    iosBundleId: 'com.example.restaurantReservation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd1trj6baevToFIeYaw2ibYS0cyqzQW9A',
    appId: '1:150769916429:web:b08921d17b6f10c3695344',
    messagingSenderId: '150769916429',
    projectId: 'restaurant-reservation-2c78f',
    authDomain: 'restaurant-reservation-2c78f.firebaseapp.com',
    storageBucket: 'restaurant-reservation-2c78f.appspot.com',
    measurementId: 'G-3LZ6QLMKES',
  );
}
